[options]
db_host = localhost
db_port = 5432
db_user = erp_user2
db_password = admin
db_name = erp_db2
http_port = 8070
dev_mode = all
addons_path = C:\Users\azizn\Desktop\ERP Transport\ERP\odoo19\addons,C:\Users\azizn\Desktop\ERP Transport\ERP\odoo19\odoo\addons,C:\Users\azizn\Desktop\ERP Transport\ERP\odoo19\odoo\custom_addons