[options]
db_host = localhost
db_port = 5432
db_user = erp_user2
db_password = admin
db_name = erp_db2
http_port = 8070
dev_mode = all
limit_time_real = 300
limit_time_cpu  = 120
addons_path = /home/user/ERP_TRANSPORT/addons,/home/user/ERP_TRANSPORT/odoo/addons,/home/user/ERP_TRANSPORT/odoo/custom_addons