# -*- coding: utf-8 -*-
{
    'name': 'Transport - Energie',
    'version': '19.0.2.0.0',
    'category': 'Transport',
    'summary': 'Gestion energie : carburant, lubrifiants, AGILIS, STEG, SONEDE',
    'author': 'ERP Transport',
    'depends': ['base', 'mail', 'fleet', 'purchase', 'stock', 'transport_boc'],
    'license': 'LGPL-3',
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/00_menus.xml',
        'views/energy_type_views.xml',
        'views/fuel_station_views.xml',
        'views/vehicle_extension_views.xml',
        'views/supply_order_views.xml',
        'views/fuel_voucher_views.xml',
        'views/bon_lubrifiant_views.xml',
        'views/jaugeage_views.xml',
        'views/jaugeage_lubrifiant_views.xml',
        'views/agilis_views.xml',
        'views/res_config_settings_views.xml',
        'views/facture_energie_views.xml',
        'views/wizard_rapport_views.xml',
        'views/wizard_rapport_energie_views.xml',
        'reports/rapport_bgi.xml',
        'reports/rapport_bge.xml',
        'reports/rapport_lubrifiant.xml',
        'reports/rapport_consommation.xml',
        'reports/rapport_distribution.xml',
        'reports/rapport_stats_agence.xml',
        'reports/rapport_rotation_chauffeurs.xml',
        'reports/rapport_vehicules_admin.xml',
        'reports/rapport_energie.xml',
    ],
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
}
