# -*- coding: utf-8 -*-
{
    'name': 'Transport - Energie',
    'version': '19.0.1.0.0',
    'category': 'Transport',
    'summary': 'Gestion de l\'énergie : carburant, lubrifiants, STEG, SONEDE',
    'author': 'ERP Transport',
    'depends': ['base', 'mail', 'fleet', 'transport_boc'],
    'license': 'LGPL-3',
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/energy_type_views.xml',
        'views/fuel_station_views.xml',
        'views/vehicle_extension_views.xml',
        'views/fuel_voucher_views.xml',
        'views/bon_lubrifiant_views.xml',
        'views/facture_energie_views.xml',
        'views/jaugeage_views.xml',
        'reports/rapport_lubrifiant.xml',
        'reports/rapport_energie.xml',
        'reports/rapport_distribution.xml',
        'views/wizard_rapport_views.xml',
        'reports/rapport_bgi.xml',
        'reports/rapport_consommation.xml',
        'views/agilis_views.xml',
    ],
    'installable': True,
    'application': True,
}